# Generated by Terraform — do not edit manually
# Droplet: ${droplet_name}

[all]
${droplet_name} ansible_host=${droplet_ip}

[all:vars]
ansible_user=${ansible_user}
ansible_ssh_private_key_file=${ansible_ssh_private_key}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
